### ISSUE TITLE
首页上方按钮

### ISSUE THREAD

**Issue by DKmrmao** [Davis-Web/HomePage#3]
对首页最上方按钮的功能做出描述

- [x]  首页，超链接，跳转到首页本身。
- [x]  副本，下拉菜单，用户鼠标悬浮，出现下拉菜单，点击对应选项跳转到相应页面。下拉菜单选项：副本一，副本二，副本三，副本四。这几个页面尚未作出，用接收邮箱功能替代跳转到相应界面
- [x] 消息，超链接，跳转到消息发布页面，消息发布页面暂时没有样式。
- [x] 社区，下拉菜单，用户鼠标悬浮，出现下拉菜单，点击对应选项跳转到相应社群链接。下拉菜单选项：Twitter，Discord，Telegram，QQ
- [x] 语言，选择语言
- [x] 加入我们，超链接，跳转到加入我们页面，加入我们页面暂时没有样式

**Comment by DKmrmao** [comment]
老哥们，搞搞？

**Comment by DavidZhang73** [comment]
> 老哥们，搞搞？

你现在能看到主页效果嘛，按钮我已经做了，但是没上传。因为持续部署还没搞出来 https://github.com/Davis-Web/HomePage/issues/1#issuecomment-930684678 我上传了也看不到做出来的样子呀。

**Comment by DKmrmao** [comment]
主页效果在哪里看> > 老哥们，搞搞？
> 
> 
> 
> 你现在能看到主页效果嘛，按钮我已经做了，但是没上传。因为持续部署还没搞出来 https://github.com/Davis-Web/HomePage/issues/1#issuecomment-930684678 我上传了也看不到做出来的样子呀。

**Comment by DavidZhang73** [comment]
> 主页效果在哪里看> > 老哥们，搞搞？
> 
> > 你现在能看到主页效果嘛，按钮我已经做了，但是没上传。因为持续部署还没搞出来 [#1 (comment)](https://github.com/Davis-Web/HomePage/issues/1#issuecomment-930684678) 我上传了也看不到做出来的样子呀。

就是这个持续部署搞好了之后，咱主页就是这个网址 [https://www.davissesa.com/](https://www.davissesa.com/)，但是现在还是原来的 WordPress 呀，然后持续部署还有没搞好，有个错误他传不上去代码。@DavisSun

**Comment by DKmrmao** [comment]
> > 主页效果在哪里看> > 老哥们，搞搞？
> > > 你现在能看到主页效果嘛，按钮我已经做了，但是没上传。因为持续部署还没搞出来 [#1 (comment)](https://github.com/Davis-Web/HomePage/issues/1#issuecomment-930684678) 我上传了也看不到做出来的样子呀。
> 
> 就是这个持续部署搞好了之后，咱主页就是这个网址 https://www.davissesa.com/，但是现在还是原来的 WordPress 呀，然后持续部署还有没搞好，有个错误他传不上去代码。@DavisSun

那咱们赶快解决一下吧，否则一直卡着也不大行

**Comment by DavidZhang73** [comment]
> > > 主页效果在哪里看> > 老哥们，搞搞？
> > > > 你现在能看到主页效果嘛，按钮我已经做了，但是没上传。因为持续部署还没搞出来 [#1 (comment)](https://github.com/Davis-Web/HomePage/issues/1#issuecomment-930684678) 我上传了也看不到做出来的样子呀。
> > 
> > 
> > 就是这个持续部署搞好了之后，咱主页就是这个网址 [https://www.davissesa.com/，但是现在还是原来的](https://www.davissesa.com/%EF%BC%8C%E4%BD%86%E6%98%AF%E7%8E%B0%E5%9C%A8%E8%BF%98%E6%98%AF%E5%8E%9F%E6%9D%A5%E7%9A%84) WordPress 呀，然后持续部署还有没搞好，有个错误他传不上去代码。@DavisSun
> 
> 那咱们赶快解决一下吧，否则一直卡着也不大行

@DavisSun
