### ISSUE TITLE
线上 history 模式适配

### ISSUE THREAD

**Issue by DavidZhang73** [Davis-Web/HomePage#5]
### 现象

访问 [首页](https://www.davissesa.com/)，然后点击 `Message`，会正确访问 `https://www.davissesa.com/message`，但是直接在地址栏访问 `https://www.davissesa.com/message` 会报错`404 Not Found`。

### 原因

因为前端采用 [`History`](https://next.router.vuejs.org/zh/guide/essentials/history-mode.html#nginx) 模式导航，所以需要使用 `try_files` 而不是 `root`。

**Comment by DavisSun** [comment]
原因
本身存在 try_files 指令 导致冲突
解决
修改/www/server/panel/vhost/rewrite 下www.davissesa.com.conf
